version: "3.3"
services:
  auth-maven:
    platform: linux/amd64
    image: ghcr.io/jayameiman/auth-maven:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"